get_water_usage_hourly_history:
  fields:
    config_entry:
      required: true
      selector:
        config_entry:
          integration: watersmart
    cached:
      required: false
      default: false
      selector:
        boolean:
    start:
      required: false
      example: "2024-01-01 00:00:00"
      selector:
        datetime:
    end:
      required: false
      example: "2024-01-01 00:00:00"
      selector:
        datetime:
